# Generated by Django 5.0.6 on 2024-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwdManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordentry",
            name="email",
            field=models.EmailField(max_length=60, verbose_name="email"),
        ),
    ]
