# Generated by Django 5.0.6 on 2024-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwdManager", "0002_alter_passwordentry_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordentry",
            name="service_name",
            field=models.CharField(max_length=100),
        ),
    ]
